I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call time_output_label
  File "game/scripts/time.rpy", line 20, in script
    $ calendar.add_current_day_time(1)
  File "game/scripts/time.rpy", line 20, in <module>
    $ calendar.add_current_day_time(1)
  File "game/scripts/events.rpy", line 19, in add_current_day_time
    add_current_day(1)
NameError: name 'add_current_day' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call time_output_label
  File "game/scripts/time.rpy", line 20, in script
    $ calendar.add_current_day_time(1)
  File "C:\Users\Luan\Documents\Work\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Luan\Documents\Work\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/time.rpy", line 20, in <module>
    $ calendar.add_current_day_time(1)
  File "game/scripts/events.rpy", line 19, in add_current_day_time
    add_current_day(1)
NameError: name 'add_current_day' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
RenpyTestProject 1.0
Wed Nov 16 20:03:17 2022
